export const ADD_ARTICLE = "ADD_ARTICLE";
export const TOGGLE_PROGRESS = "TOGGLE_PROGRESS";

export const PROGRESS_NOT_STARTED = "PROGRESS_NOT_STARTED",
    PROGRESS_ONE_FOURTH = "PROGRESS_ONE_FOURTH",
    PROGRESS_ONE_HALF = "PROGRESS_ONE_HALF",
    PROGRESS_THREE_FOURTHS = "PROGRESS_THREE_FOURTHS",
    PROGRESS_COMPLETE = "PROGRESS_COMPLETE";